---
# tasks file for flatpaks

- name: Ensure the /etc/skel.d/.config/autostart/ directory exists
  file:
    path: /etc/skel.d/.config/autostart/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy 'flatpak-setup.desktop' file to /etc/skel.d/.config/autostart/
  copy:
    - src: 'files/flatpak-setup.desktop'
    - dest: '/etc/skel.d/.config/autostart/flatpak-setup.desktop'

- name: Create flatpak installation script at /usr/bin/ansible-silverblue-flatpak
  ansible.builtin.template:
    src: templates/ansible-silverblue-flatpaks.jinja2
    dest: /usr/bin/ansible-silverblue-flatpak
    owner: root
    group: root
    mode: 0644
