---
# tasks file for build_cleanup

- name: Remove files that get put in /var. Otherwise, the build will fail
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ post_build_artifacts }}"

- name: Clean the ostree repository of metadata to reduce the image size
  command: rpm-ostree cleanup -m
