---

- hosts: all
  gather_facts: false
  roles:
    - { role: copr_repos }
    - { role: layered_packages }
    - { role: flatpaks }
#   - { role: google_cloud_sdk }
    - { role: gnome_settings }
    - { role: system_and_flatpak_updates }
    - { role: verify_build }
    - { role: build_cleanup }
