---
# tasks file for onepassword

- name: Install the 1password yum repository
  yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey:
      - https://downloads.1password.com/linux/keys/1password.asc

- name: Install 1password
  community.general.rpm_ostree_pkg:
    name: 1password
    state: present
